In [1]:
import numpy as np
import pandas as pd

In [2]:
train = pd.read_csv('../input/no-title/train_dataset.csv')
train.head()

,ID,N_Days,Status,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,7135,1654,CL,D-penicillamine,19581,F,N,N,Y,N,0.3,279.0,2.96,84.0,1500.8,99.43,109.0,293.0,10.2,4.0
1,7326,41,C,D-penicillamine,22880,F,NaN,N,NaN,N,0.3,NaN,2.96,NaN,1835.4,26.35,131.0,308.0,10.8,1.0
2,7254,297,D,NaN,27957,F,N,N,NaN,N,0.3,328.0,2.64,4.0,NaN,NaN,116.0,194.0,10.3,3.0
3,3135,1872,C,D-penicillamine,21111,F,NaN,Y,Y,N,0.3,302.0,2.02,49.0,NaN,26.35,NaN,NaN,10.5,4.0
4,2483,939,CL,D-penicillamine,18061,F,NaN,NaN,NaN,N,0.5,344.0,3.11,91.0,NaN,104.56,NaN,306.0,11.4,2.0

In [3]:
test = pd.read_csv('../input/no-title/test_dataset.csv')
test.head()

,ID,N_Days,Status,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin
0,3870,41,C,Placebo,22553,F,N,NaN,N,N,1.4,247.0,3.62,NaN,NaN,108.65,NaN,169.0,11.6
1,3462,1811,C,D-penicillamine,16223,F,N,Y,N,N,0.3,311.0,2.80,92.0,1748.1,NaN,129.0,321.0,11.5
2,1632,954,C,D-penicillamine,27100,F,N,N,N,N,0.4,NaN,3.56,NaN,NaN,43.52,NaN,296.0,10.3
3,722,1969,D,Placebo,17039,F,N,Y,N,N,1.2,NaN,3.16,NaN,617.1,113.76,NaN,125.0,10.9
4,1000,2721,D,D-penicillamine,17738,F,NaN,NaN,NaN,N,3.2,NaN,2.36,89.0,1782.4,NaN,129.0,138.0,10.6

In [4]:
train.isnull().sum()

ID                  0
N_Days              0
Status              0
Drug             2025
Age                 0
Sex                 0
Ascites          2246
Hepatomegaly     2427
Spiders          2590
Edema               0
Bilirubin           0
Cholesterol      3101
Albumin             0
Copper           2156
Alk_Phos         2498
SGOT             2102
Tryglicerides    2812
Platelets         338
Prothrombin       155
Stage               0
dtype: int64

In [5]:
test.isnull().sum()

ID                  0
N_Days              0
Status              0
Drug              963
Age                 0
Sex                 0
Ascites          1087
Hepatomegaly     1102
Spiders          1200
Edema               0
Bilirubin           0
Cholesterol      1435
Albumin             0
Copper           1006
Alk_Phos         1168
SGOT              987
Tryglicerides    1286
Platelets         164
Prothrombin        64
dtype: int64

In [6]:
train = train.fillna(train.mode().iloc[0])
train.head()

,ID,N_Days,Status,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,7135,1654,CL,D-penicillamine,19581,F,N,N,Y,N,0.3,279.0,2.96,84.0,1500.8,99.43,109.0,293.0,10.2,4.0
1,7326,41,C,D-penicillamine,22880,F,N,N,N,N,0.3,120.0,2.96,4.0,1835.4,26.35,131.0,308.0,10.8,1.0
2,7254,297,D,D-penicillamine,27957,F,N,N,N,N,0.3,328.0,2.64,4.0,289.0,26.35,116.0,194.0,10.3,3.0
3,3135,1872,C,D-penicillamine,21111,F,N,Y,Y,N,0.3,302.0,2.02,49.0,289.0,26.35,130.0,563.0,10.5,4.0
4,2483,939,CL,D-penicillamine,18061,F,N,N,N,N,0.5,344.0,3.11,91.0,289.0,104.56,130.0,306.0,11.4,2.0

In [7]:
train.isnull().sum()

ID               0
N_Days           0
Status           0
Drug             0
Age              0
Sex              0
Ascites          0
Hepatomegaly     0
Spiders          0
Edema            0
Bilirubin        0
Cholesterol      0
Albumin          0
Copper           0
Alk_Phos         0
SGOT             0
Tryglicerides    0
Platelets        0
Prothrombin      0
Stage            0
dtype: int64

In [8]:
test = test.fillna(test.mode().iloc[0])
test.head()

,ID,N_Days,Status,Drug,Age,Sex,Ascites,Hepatomegaly,Spiders,Edema,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin
0,3870,41,C,Placebo,22553,F,N,N,N,N,1.4,247.0,3.62,4.0,289.0,108.65,125.0,169.0,11.6
1,3462,1811,C,D-penicillamine,16223,F,N,Y,N,N,0.3,311.0,2.80,92.0,1748.1,26.35,129.0,321.0,11.5
2,1632,954,C,D-penicillamine,27100,F,N,N,N,N,0.4,120.0,3.56,4.0,289.0,43.52,125.0,296.0,10.3
3,722,1969,D,Placebo,17039,F,N,Y,N,N,1.2,120.0,3.16,4.0,617.1,113.76,125.0,125.0,10.9
4,1000,2721,D,D-penicillamine,17738,F,N,N,N,N,3.2,120.0,2.36,89.0,1782.4,26.35,129.0,138.0,10.6

In [9]:
test.shape

(3200, 19)

In [10]:
test.isnull().sum()

ID               0
N_Days           0
Status           0
Drug             0
Age              0
Sex              0
Ascites          0
Hepatomegaly     0
Spiders          0
Edema            0
Bilirubin        0
Cholesterol      0
Albumin          0
Copper           0
Alk_Phos         0
SGOT             0
Tryglicerides    0
Platelets        0
Prothrombin      0
dtype: int64

In [11]:
import category_encoders as ce
ce_OHE = ce.OneHotEncoder(cols=['Status','Drug','Sex','Ascites','Hepatomegaly','Spiders','Edema'])

train = ce_OHE.fit_transform(train)
train.head()

,ID,N_Days,Status_1,Status_2,Status_3,Drug_1,Drug_2,Age,Sex_1,Sex_2,...,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin,Stage
0,7135,1654,1,0,0,1,0,19581,1,0,...,0.3,279.0,2.96,84.0,1500.8,99.43,109.0,293.0,10.2,4.0
1,7326,41,0,1,0,1,0,22880,1,0,...,0.3,120.0,2.96,4.0,1835.4,26.35,131.0,308.0,10.8,1.0
2,7254,297,0,0,1,1,0,27957,1,0,...,0.3,328.0,2.64,4.0,289.0,26.35,116.0,194.0,10.3,3.0
3,3135,1872,0,1,0,1,0,21111,1,0,...,0.3,302.0,2.02,49.0,289.0,26.35,130.0,563.0,10.5,4.0
4,2483,939,1,0,0,1,0,18061,1,0,...,0.5,344.0,3.11,91.0,289.0,104.56,130.0,306.0,11.4,2.0

In [12]:
test = ce_OHE.fit_transform(test)
test.head()

,ID,N_Days,Status_1,Status_2,Status_3,Drug_1,Drug_2,Age,Sex_1,Sex_2,...,Edema_3,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin
0,3870,41,1,0,0,1,0,22553,1,0,...,0,1.4,247.0,3.62,4.0,289.0,108.65,125.0,169.0,11.6
1,3462,1811,1,0,0,0,1,16223,1,0,...,0,0.3,311.0,2.80,92.0,1748.1,26.35,129.0,321.0,11.5
2,1632,954,1,0,0,0,1,27100,1,0,...,0,0.4,120.0,3.56,4.0,289.0,43.52,125.0,296.0,10.3
3,722,1969,0,1,0,1,0,17039,1,0,...,0,1.2,120.0,3.16,4.0,617.1,113.76,125.0,125.0,10.9
4,1000,2721,0,1,0,0,1,17738,1,0,...,0,3.2,120.0,2.36,89.0,1782.4,26.35,129.0,138.0,10.6

In [13]:
X = train
y = test

In [14]:
X_train = X.iloc[:, :-1]
y_train = X.iloc[:,-1]

In [15]:
X_test = y

In [16]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error as MSE

In [17]:
X_train.dtypes

ID                  int64
N_Days              int64
Status_1            int64
Status_2            int64
Status_3            int64
Drug_1              int64
Drug_2              int64
Age                 int64
Sex_1               int64
Sex_2               int64
Ascites_1           int64
Ascites_2           int64
Hepatomegaly_1      int64
Hepatomegaly_2      int64
Spiders_1           int64
Spiders_2           int64
Edema_1             int64
Edema_2             int64
Edema_3             int64
Bilirubin         float64
Cholesterol       float64
Albumin           float64
Copper            float64
Alk_Phos          float64
SGOT              float64
Tryglicerides     float64
Platelets         float64
Prothrombin       float64
dtype: object

In [18]:
X_train.head()

,ID,N_Days,Status_1,Status_2,Status_3,Drug_1,Drug_2,Age,Sex_1,Sex_2,...,Edema_3,Bilirubin,Cholesterol,Albumin,Copper,Alk_Phos,SGOT,Tryglicerides,Platelets,Prothrombin
0,7135,1654,1,0,0,1,0,19581,1,0,...,0,0.3,279.0,2.96,84.0,1500.8,99.43,109.0,293.0,10.2
1,7326,41,0,1,0,1,0,22880,1,0,...,0,0.3,120.0,2.96,4.0,1835.4,26.35,131.0,308.0,10.8
2,7254,297,0,0,1,1,0,27957,1,0,...,0,0.3,328.0,2.64,4.0,289.0,26.35,116.0,194.0,10.3
3,3135,1872,0,1,0,1,0,21111,1,0,...,0,0.3,302.0,2.02,49.0,289.0,26.35,130.0,563.0,10.5
4,2483,939,1,0,0,1,0,18061,1,0,...,0,0.5,344.0,3.11,91.0,289.0,104.56,130.0,306.0,11.4

In [19]:
import xgboost as xg
from sklearn.metrics import mean_squared_error as MSE
from sklearn import datasets, linear_model, metrics


reg = linear_model.LinearRegression()
 
# train the model using the training sets
reg.fit(X_train, y_train)

 
# regression coefficients
print('Coefficients: ', reg.coef_)

Coefficients:  [-7.73119829e-05  3.71091957e-06  3.43441580e-02  1.02319940e-02
 -4.45761520e-02 -3.24855965e-03  3.24855965e-03  7.25954569e-07
 -1.26267630e-02  1.26267630e-02  6.77717078e-03 -6.77717078e-03
  1.87428845e-02 -1.87428845e-02 -7.70261205e-03  7.70261205e-03
 -3.61730639e-02  2.08980001e-02  1.52750637e-02 -2.22411611e-03
  2.64528207e-04 -3.39835604e-02  2.06546305e-04  8.36979439e-07
 -5.60379202e-04 -8.99728480e-04 -1.84900104e-04  6.21679924e-03]

In [20]:
import matplotlib.pyplot as plt

In [21]:

# Instantiation
xgb_r = xg.XGBRegressor(objective ='reg:linear',
                  n_estimators = 10, seed = 123)
  
# Fitting the model
xgb_r.fit(X_train, y_train)
  
# Predict the model
pred = xgb_r.predict(X_test)

[11:34:34] WARNING: ../src/objective/regression_obj.cu:188: reg:linear is now deprecated in favor of reg:squarederror.

In [22]:
type(pred)

numpy.ndarray

In [23]:
df = pd.DataFrame(pred, columns = ['Stage'])

In [24]:
df.head()

      Stage
0  3.494691
1  3.460125
2  3.900434
3  3.876073
4  3.888951

In [25]:
df = df.round()

In [26]:
df.head()

   Stage
0    3.0
1    3.0
2    4.0
3    4.0
4    4.0

In [27]:
df.to_csv('./Output1.csv')

In [28]:
from sklearn.tree import DecisionTreeRegressor 
  
# create a regressor object
regressor = DecisionTreeRegressor(random_state = 0) 
regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

In [29]:
y_pred = regressor.predict(X_test)

In [30]:
df1 = pd.DataFrame(y_pred, columns = ['Stage'])

In [31]:
df1.head

<bound method NDFrame.head of       Stage
0       4.0
1       4.0
2       4.0
3       4.0
4       4.0
...     ...
3195    4.0
3196    4.0
3197    4.0
3198    4.0
3199    4.0

[3200 rows x 1 columns]>

In [32]:
df1.to_csv('./Output_dt.csv')